# This is free software, lisence use MIT.
# Copyright (C) https://github.com/yfdoor

name: Create Release

on:
  #push:
  #  tags:
  #    - 'v*'
  #schedule:
  #  - cron: 0 0 */3 * *
  watch:
    types: started

jobs:
  Create-Release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: $(TZ=UTC-8 date +"%Y.%m.%d")
          release_name: Release $(TZ=UTC-8 date +"%Y.%m.%d") by YFDOOR
          body: |
            Changes in this Release
            - First Change
            - Second Change
            - 🚀 Automated build | 自动编译
          draft: false
          prerelease: false
