# This is free software, lisence use MIT.
# Copyright (C) https://github.com/yfdoor

name: Create Release

on:
  #push:
  #  tags:
  #    - 'v*'
  #schedule:
  #  - cron: 0 0 */3 * *
  watch:
    types: started

jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Generate tag
        run: |
          echo ::set-env name=RELEASE_TAG::"$(TZ=UTC-8 date +"%Y.%m.%d")"  

      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          body: |
            - Release by YFDOOR
            - Automated build | 自动编译
          draft: false
          prerelease: false
