# This is free software, lisence use MIT.
# Copyright (C) https://github.com/yfdoor

name: Create-Release

on:
  #schedule:
  #  - cron: 0 0 */3 * *
  watch:
    types: started

jobs:
  Create-Release:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Tag
        run: |
          echo ::set-env name=RELEASE_TAG::"$(TZ=UTC-8 date +"%Y.%m.%d")"
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          body: 🚀 Automated build | 自动编译
