# This is free software, lisence use MIT.
# Copyright (C) https://github.com/yfdoor

name: Create-Release

on:
  #push:
  #  tags:
  #    - 'v*'
  schedule:
    - cron: 0 0 * * 5
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: Generate tag           
        run: |
          echo ::set-env name=RELEASE_TAG::"$(TZ=UTC-8 date +"%Y.%m.%d")"

      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: V_${{ env.RELEASE_TAG }}_tag
          release_name: V_${{ env.RELEASE_TAG }}
          body: |
            Build @ By YFDOOR
            🚀 Automated build | 自动编译
          draft: false
          prerelease: false
