# This is free software, lisence use MIT.
# Copyright (C) https://github.com/yfdoor
#
# https://github.com/yfdoor/OpenWrt
# Description: GitHub Actions for OpenWrt Build

name: try

# 触发条件
on:
  #  push:
  #    branches:
  #      - master
  #    paths:
  #      - '.config'
  #schedule:
  #   - cron: 0 0 1/6 * *
  watch:
     types: started

# 环境定义
env:
  #####################################################
  #####   1：编译官方源码
  #####   2：编译第三方源码
  #####   3：编译官方源码 & 第三方 Package
  #####################################################
  ## REPO_URL: https://github.com/openwrt/openwrt.git
  REPO_URL: https://github.com/coolsnowwolf/lede.git
  ## REPO_URL: https://github.com/Lienol/openwrt.git
  REPO_BRANCH: master
  CONF_FILE: x86_64
  DIY0_FILE: DIY0.sh
  DIY1_FILE: DIY1.sh
  PKG_LEAN: true
  PKG_LIENOL: true
  SSH_ACTION: false
  UPLOAD_BRANCH: true
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  #####################################################

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      # 项目初始
      - name: Code Checkout
        uses: actions/checkout@main

      # 初始环境
      - name: Try
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ" 

          export hh=$(date)
          echo $hh
          echo "RELEASE=$(hh +"%Y%m%d%H%M")" >> $GITHUB_ENV
          echo "TAG=$(hh +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
          echo ${{ env.RELEASE }}
          echo ${{ env.TAG }}
